name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache SonarScanner
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-scanner-cli-7.0.2
        restore-keys: |
          ${{ runner.os }}-sonar-scanner-cli-7.0.2

    - name: Set up SonarScanner
      uses: SonarSource/sonarqube-scan-action@v5
      with:
        sonarHostUrl: ${{ secrets.SONARQUBE_URL }}  # Inserisci l'URL del tuo server SonarQube o SonarCloud
        sonarToken: ${{ secrets.SONARQUBE_TOKEN }}  # Token di autenticazione

    - name: Run SonarScanner
      run: |
        echo "sonar.projectKey=enricobarbatano_esperimento" >> $GITHUB_ENV
        echo "sonar.organization=enricobarbatano" >> $GITHUB_ENV
        echo "sonar.sources=src" >> $GITHUB_ENV
        echo "sonar.java.binaries=./bin" >> $GITHUB_ENV
        echo "sonar.exclusions=**/*.java" >> $GITHUB_ENV
        echo "sonar.sourceEncoding=UTF-8" >> $GITHUB_ENV
        sonar-scanner.bat


