name: SonarCloud Scan

on:
  push:
    branches:
      - main  # Esegui l'analisi su push al ramo "main"
  pull_request:
    branches:
      - main  # Esegui l'analisi anche su pull request al ramo "main"

jobs:
  sonarcloud:
    runs-on: ubuntu-latest  # Puoi usare windows-latest se desideri

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache SonarCloud analysis results
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          ${{ runner.os }}-sonarcloud-

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        sonar-cloud-token: ${{ secrets.SONAR_TOKEN }}  # Aggiungi il tuo token come secret su GitHub
        sonar-project-key: <your_project_key>
        sonar-organization: <your_organization_key>
